detection:
  min_detection_confidence: 0.8
  min_tracking_confidence: 0.5
  max_num_hands: 1 # Максимальное колличество распозноваемых рук


camera:
  ids: [0, 1] # Список камер, задается обязательно в квадратных скобках, через запятую. Например [0, 1, 2],
  mode: "stream" # Доступные режимы: "stream", "video", "frame"
  width: 640 # Ширина
  height: 480 # Высота

fingers:
  wrist: [0]
  thumb: [4, 1]
  index: [8, 5]
  middle: [12, 9]
  ring: [16, 13]
  pinky: [20, 17]